<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE trakem2_anything [
	<!ELEMENT trakem2 (project,t2_layer_set,t2_display)>
	<!ELEMENT project (anything)>
	<!ATTLIST project id NMTOKEN #REQUIRED>
	<!ATTLIST project unuid NMTOKEN #REQUIRED>
	<!ATTLIST project title NMTOKEN #REQUIRED>
	<!ATTLIST project preprocessor NMTOKEN #REQUIRED>
	<!ATTLIST project mipmaps_folder NMTOKEN #REQUIRED>
	<!ATTLIST project storage_folder NMTOKEN #REQUIRED>
	<!ELEMENT anything (area_list)>
	<!ATTLIST anything id NMTOKEN #REQUIRED>
	<!ATTLIST anything expanded NMTOKEN #REQUIRED>
	<!ELEMENT area_list EMPTY>
	<!ATTLIST area_list id NMTOKEN #REQUIRED>
	<!ATTLIST area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST area_list expanded NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer (t2_patch,t2_label,t2_layer_set,t2_profile)>
	<!ATTLIST t2_layer oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer thickness NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer z NMTOKEN #REQUIRED>
	<!ELEMENT t2_layer_set (t2_prop,t2_linked_prop,t2_annot,t2_layer,t2_pipe,t2_ball,t2_area_list,t2_calibration,t2_stack,t2_treeline)>
	<!ATTLIST t2_layer_set oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set style NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set title NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set links NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set layer_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set rot_z NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set snapshots_quality NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set area_color_cues NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set avoid_color_cue_colors NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set n_layers_color_cue NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_arrows NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_tags NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set paint_edge_confidence_boxes NMTOKEN #REQUIRED>
	<!ATTLIST t2_layer_set preload_ahead NMTOKEN #REQUIRED>
	<!ELEMENT t2_calibration EMPTY>
	<!ATTLIST t2_calibration pixelWidth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelHeight NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration pixelDepth NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration xOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration yOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration zOrigin NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration info NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration valueUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration timeUnit NMTOKEN #REQUIRED>
	<!ATTLIST t2_calibration unit NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball (t2_prop,t2_linked_prop,t2_annot,t2_ball_ob)>
	<!ATTLIST t2_ball oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball style NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball title NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball links NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball fill NMTOKEN #REQUIRED>
	<!ELEMENT t2_ball_ob EMPTY>
	<!ATTLIST t2_ball_ob x NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob y NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob r NMTOKEN #REQUIRED>
	<!ATTLIST t2_ball_ob layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_label (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_label oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_label layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_label transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_label style NMTOKEN #REQUIRED>
	<!ATTLIST t2_label locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_label visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_label title NMTOKEN #REQUIRED>
	<!ATTLIST t2_label links NMTOKEN #REQUIRED>
	<!ATTLIST t2_label composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_filter EMPTY>
	<!ELEMENT t2_patch (t2_prop,t2_linked_prop,t2_annot,ict_transform,ict_transform_list,t2_filter)>
	<!ATTLIST t2_patch oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch style NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch title NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch links NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch file_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch original_path NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch type NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch false_color NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch min NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch max NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch o_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch pps NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch mres NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch ct_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_patch alpha_mask_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_pipe (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_pipe oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe style NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe title NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe links NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe d NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe p_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_pipe layer_ids NMTOKEN #REQUIRED>
	<!ELEMENT t2_polyline (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_polyline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_polyline d NMTOKEN #REQUIRED>
	<!ELEMENT t2_profile (t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_profile oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile style NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile title NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile links NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_profile d NMTOKEN #REQUIRED>
	<!ELEMENT t2_area_list (t2_prop,t2_linked_prop,t2_annot,t2_area)>
	<!ATTLIST t2_area_list oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list style NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list title NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list links NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_area_list fill_paint NMTOKEN #REQUIRED>
	<!ELEMENT t2_area (t2_path)>
	<!ATTLIST t2_area layer_id NMTOKEN #REQUIRED>
	<!ELEMENT t2_path EMPTY>
	<!ATTLIST t2_path d NMTOKEN #REQUIRED>
	<!ELEMENT t2_dissector (t2_prop,t2_linked_prop,t2_annot,t2_dd_item)>
	<!ATTLIST t2_dissector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_dissector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_dd_item EMPTY>
	<!ATTLIST t2_dd_item radius NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item tag NMTOKEN #REQUIRED>
	<!ATTLIST t2_dd_item points NMTOKEN #REQUIRED>
	<!ELEMENT t2_stack (t2_prop,t2_linked_prop,t2_annot,(iict_transform|iict_transform_list)?)>
	<!ATTLIST t2_stack oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack style NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack title NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack links NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack composite NMTOKEN #REQUIRED>
	<!ATTLIST t2_stack file_path CDATA #REQUIRED>
	<!ATTLIST t2_stack depth CDATA #REQUIRED>
	<!ELEMENT t2_tag EMPTY>
	<!ATTLIST t2_tag name NMTOKEN #REQUIRED>
	<!ATTLIST t2_tag key NMTOKEN #REQUIRED>
	<!ELEMENT t2_node (t2_area*,t2_tag*)>
	<!ATTLIST t2_node x NMTOKEN #REQUIRED>
	<!ATTLIST t2_node y NMTOKEN #REQUIRED>
	<!ATTLIST t2_node lid NMTOKEN #REQUIRED>
	<!ATTLIST t2_node c NMTOKEN #REQUIRED>
	<!ATTLIST t2_node r NMTOKEN #IMPLIED>
	<!ELEMENT t2_treeline (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_treeline oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline style NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline title NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline links NMTOKEN #REQUIRED>
	<!ATTLIST t2_treeline composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_areatree (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_areatree oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree style NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree title NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree links NMTOKEN #REQUIRED>
	<!ATTLIST t2_areatree composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_connector (t2_node*,t2_prop,t2_linked_prop,t2_annot)>
	<!ATTLIST t2_connector oid NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector transform NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector style NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector locked NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector visible NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector title NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector links NMTOKEN #REQUIRED>
	<!ATTLIST t2_connector composite NMTOKEN #REQUIRED>
	<!ELEMENT t2_prop EMPTY>
	<!ATTLIST t2_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_linked_prop EMPTY>
	<!ATTLIST t2_linked_prop target_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop key NMTOKEN #REQUIRED>
	<!ATTLIST t2_linked_prop value NMTOKEN #REQUIRED>
	<!ELEMENT t2_annot EMPTY>
	<!ELEMENT t2_display EMPTY>
	<!ATTLIST t2_display id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display layer_id NMTOKEN #REQUIRED>
	<!ATTLIST t2_display x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display magnification NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_x NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_y NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_width NMTOKEN #REQUIRED>
	<!ATTLIST t2_display srcrect_height NMTOKEN #REQUIRED>
	<!ATTLIST t2_display scroll_step NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas NMTOKEN #REQUIRED>
	<!ATTLIST t2_display c_alphas_state NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min_max_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_min NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_max NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_invert NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_enabled NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_block_size NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_histogram_bins NMTOKEN #REQUIRED>
	<!ATTLIST t2_display filter_clahe_max_slope NMTOKEN #REQUIRED>
	<!ELEMENT ict_transform EMPTY>
	<!ATTLIST ict_transform class CDATA #REQUIRED>
	<!ATTLIST ict_transform data CDATA #REQUIRED>
	<!ELEMENT iict_transform EMPTY>
	<!ATTLIST iict_transform class CDATA #REQUIRED>
	<!ATTLIST iict_transform data CDATA #REQUIRED>
	<!ELEMENT ict_transform_list (ict_transform|iict_transform)*>
	<!ELEMENT iict_transform_list (iict_transform*)>
] >

<trakem2>
	<project 
		id="0"
		title="nuclei"
		unuid="1516895714891.2129023645.415840246"
		mipmaps_folder="/Users/maxhaase/Desktop/Grad_School/Rotation_lionnet/SRF/20180112_FISH/SRF/20180112_SRF/0min_75K/exp_1/trakem2.1516895714891.2129023645.415840246/trakem2.mipmaps/"
		storage_folder="/Users/maxhaase/Desktop/Grad_School/Rotation_lionnet/SRF/20180112_FISH/SRF/20180112_SRF/0min_75K/exp_1/"
		mipmaps_format="4"
		image_resizing_mode="Area downsampling"
	>
		<anything id="211" title="exp1" expanded="true">
			<area_list id="214" oid="213"/>
		</anything>
		<anything id="217" title="exp2">
		</anything>
	</project>
	<t2_layer_set
		oid="3"
		width="20.0"
		height="20.0"
		transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
		title="Top Level"
		links=""
		layer_width="512.0"
		layer_height="512.0"
		rot_x="0.0"
		rot_y="0.0"
		rot_z="0.0"
		snapshots_quality="true"
		snapshots_mode="Full"
		color_cues="true"
		area_color_cues="true"
		avoid_color_cue_colors="false"
		n_layers_color_cue="0"
		paint_arrows="true"
		paint_tags="true"
		paint_edge_confidence_boxes="true"
		prepaint="false"
		preload_ahead="0"
	>
		<t2_calibration
			pixelWidth="2.3283064370807974E-6"
			pixelHeight="2.3283064370807974E-6"
			pixelDepth="0.1999999999998181"
			xOrigin="0.0"
			yOrigin="0.0"
			zOrigin="0.0"
			info="null"
			valueUnit="Gray Value"
			timeUnit="sec"
			unit="µm"
		/>
		<t2_area_list
			oid="213"
			width="151.0"
			height="173.0"
			transform="matrix(1.0,0.0,0.0,1.0,134.0,157.0)"
			title="area_list"
			links="150"
			layer_set_id="3"
			fill_paint="true"
			style="stroke:none;fill-opacity:0.4;fill:#ffff00;"
		>
			<t2_area layer_id="148">
				<t2_path d="M 46 0 L 46 1 L 41 1 L 41 2 L 38 2 L 38 3 L 36 3 L 36 4 L 33 4 L 33 5 L 31 5 L 31 6 L 29 6 L 29 7 L 27 7 L 27 8 L 26 8 L 26 9 L 24 9 L 24 10 L 23 10 L 23 11 L 21 11 L 21 12 L 20 12 L 20 13 L 19 13 L 19 14 L 18 14 L 18 15 L 17 15 L 17 16 L 16 16 L 16 17 L 15 17 L 15 18 L 14 18 L 14 19 L 13 19 L 13 20 L 12 20 L 12 21 L 11 21 L 11 22 L 10 22 L 10 23 L 9 23 L 9 25 L 8 25 L 8 28 L 7 28 L 7 31 L 6 31 L 6 34 L 5 34 L 5 37 L 4 37 L 4 42 L 4 45 L 4 46 L 3 46 L 3 49 L 2 49 L 2 54 L 1 54 L 1 59 L 0 59 L 0 64 L 0 67 L 1 67 L 1 69 L 1 70 L 1 72 L 1 75 L 2 75 L 2 77 L 2 79 L 2 82 L 3 82 L 3 84 L 4 84 L 4 86 L 4 88 L 5 88 L 5 90 L 5 91 L 5 92 L 6 92 L 6 94 L 6 95 L 7 95 L 7 97 L 7 98 L 8 98 L 8 100 L 8 101 L 9 101 L 9 103 L 10 103 L 10 104 L 10 105 L 11 105 L 11 107 L 12 107 L 12 109 L 13 109 L 13 111 L 14 111 L 14 113 L 14 115 L 15 115 L 15 117 L 16 117 L 16 118 L 17 118 L 17 120 L 17 121 L 18 121 L 18 123 L 19 123 L 19 124 L 19 125 L 20 125 L 20 127 L 21 127 L 21 128 L 22 128 L 22 129 L 23 129 L 23 130 L 24 130 L 24 131 L 25 131 L 25 133 L 26 133 L 26 134 L 27 134 L 27 136 L 28 136 L 28 138 L 29 138 L 29 140 L 30 140 L 30 142 L 31 142 L 31 143 L 32 143 L 32 144 L 33 144 L 33 146 L 34 146 L 34 147 L 35 147 L 35 148 L 36 148 L 36 149 L 37 149 L 37 150 L 38 150 L 38 151 L 39 151 L 39 152 L 40 152 L 40 153 L 41 153 L 41 154 L 42 154 L 42 155 L 43 155 L 43 156 L 44 156 L 44 157 L 46 157 L 46 158 L 47 158 L 47 159 L 48 159 L 48 160 L 50 160 L 50 161 L 51 161 L 51 162 L 52 162 L 52 163 L 53 163 L 53 164 L 55 164 L 55 165 L 56 165 L 56 166 L 58 166 L 58 167 L 60 167 L 60 168 L 62 168 L 62 169 L 63 169 L 63 170 L 65 170 L 65 171 L 68 171 L 68 172 L 70 172 L 70 173 L 103 173 L 103 172 L 105 172 L 105 171 L 107 171 L 107 170 L 109 170 L 109 169 L 111 169 L 111 168 L 113 168 L 113 167 L 115 167 L 115 166 L 117 166 L 117 165 L 119 165 L 119 164 L 120 164 L 120 163 L 121 163 L 121 162 L 122 162 L 122 161 L 123 161 L 123 160 L 124 160 L 124 159 L 125 159 L 125 158 L 127 158 L 127 157 L 128 157 L 128 156 L 129 156 L 129 155 L 130 155 L 130 154 L 132 154 L 132 153 L 133 153 L 133 152 L 134 152 L 134 151 L 135 151 L 135 149 L 136 149 L 136 148 L 137 148 L 137 147 L 138 147 L 138 146 L 139 146 L 139 144 L 140 144 L 140 143 L 141 143 L 141 141 L 142 141 L 142 139 L 143 139 L 143 137 L 144 137 L 144 132 L 145 132 L 145 127 L 146 127 L 146 122 L 147 122 L 147 120 L 148 120 L 148 117 L 149 117 L 149 115 L 150 115 L 150 110 L 151 110 L 151 107 L 151 102 L 151 97 L 151 92 L 151 87 L 150 87 L 150 83 L 149 83 L 149 81 L 148 81 L 148 77 L 147 77 L 147 75 L 146 75 L 146 73 L 145 73 L 145 71 L 144 71 L 144 67 L 143 67 L 143 65 L 142 65 L 142 64 L 141 64 L 141 63 L 140 63 L 140 62 L 139 62 L 139 60 L 138 60 L 138 59 L 137 59 L 137 57 L 136 57 L 136 56 L 135 56 L 135 54 L 134 54 L 134 51 L 133 51 L 133 50 L 133 45 L 132 45 L 132 44 L 132 40 L 134 40 L 134 39 L 135 39 L 135 38 L 136 38 L 136 36 L 137 36 L 137 31 L 136 31 L 136 29 L 135 29 L 135 27 L 134 27 L 134 26 L 133 26 L 133 25 L 131 25 L 131 24 L 129 24 L 129 23 L 127 23 L 127 22 L 125 22 L 125 21 L 123 21 L 123 19 L 122 19 L 122 18 L 121 18 L 121 17 L 119 17 L 119 16 L 114 16 L 114 17 L 112 17 L 112 18 L 107 18 L 107 19 L 105 19 L 105 20 L 104 20 L 104 21 L 102 21 L 102 20 L 101 20 L 101 19 L 99 19 L 99 18 L 98 18 L 98 17 L 96 17 L 96 16 L 95 16 L 95 15 L 93 15 L 93 14 L 91 14 L 91 13 L 90 13 L 90 12 L 89 12 L 89 11 L 87 11 L 87 10 L 85 10 L 85 9 L 83 9 L 83 8 L 82 8 L 82 7 L 80 7 L 80 6 L 77 6 L 77 5 L 75 5 L 75 4 L 70 4 L 70 3 L 64 3 L 64 2 L 59 2 L 59 1 L 53 1 L 53 0 z" />
			</t2_area>
		</t2_area_list>
		<t2_layer oid="5"
			 thickness="2.0"
			 z="0.0"
			 title=""
		>
			<t2_patch
				oid="9"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 1"
				links="12"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=1"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="10"
			 thickness="2.0"
			 z="2.0"
			 title=""
		>
			<t2_patch
				oid="12"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 2"
				links="9,15"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=2"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="13"
			 thickness="2.0"
			 z="4.0"
			 title=""
		>
			<t2_patch
				oid="15"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 3"
				links="12,18"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=3"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="16"
			 thickness="2.0"
			 z="6.0"
			 title=""
		>
			<t2_patch
				oid="18"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 4"
				links="15,21"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=4"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="19"
			 thickness="2.0"
			 z="8.0"
			 title=""
		>
			<t2_patch
				oid="21"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 5"
				links="18,24"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=5"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="22"
			 thickness="2.0"
			 z="10.0"
			 title=""
		>
			<t2_patch
				oid="24"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 6"
				links="21,27"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=6"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="25"
			 thickness="2.0"
			 z="12.0"
			 title=""
		>
			<t2_patch
				oid="27"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 7"
				links="24,30"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=7"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="28"
			 thickness="2.0"
			 z="14.0"
			 title=""
		>
			<t2_patch
				oid="30"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 8"
				links="27,33"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=8"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="31"
			 thickness="2.0"
			 z="16.0"
			 title=""
		>
			<t2_patch
				oid="33"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 9"
				links="30,36"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=9"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="34"
			 thickness="2.0"
			 z="18.0"
			 title=""
		>
			<t2_patch
				oid="36"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 10"
				links="33,39"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=10"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="37"
			 thickness="2.0"
			 z="20.0"
			 title=""
		>
			<t2_patch
				oid="39"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 11"
				links="36,42"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=11"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="40"
			 thickness="2.0"
			 z="22.0"
			 title=""
		>
			<t2_patch
				oid="42"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 12"
				links="39,45"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=12"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="43"
			 thickness="2.0"
			 z="24.0"
			 title=""
		>
			<t2_patch
				oid="45"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 13"
				links="42,48"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=13"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="46"
			 thickness="2.0"
			 z="26.0"
			 title=""
		>
			<t2_patch
				oid="48"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 14"
				links="45,51"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=14"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="49"
			 thickness="2.0"
			 z="28.0"
			 title=""
		>
			<t2_patch
				oid="51"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 15"
				links="48,54"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=15"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="52"
			 thickness="2.0"
			 z="30.0"
			 title=""
		>
			<t2_patch
				oid="54"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 16"
				links="51,57"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=16"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="55"
			 thickness="2.0"
			 z="32.0"
			 title=""
		>
			<t2_patch
				oid="57"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 17"
				links="54,60"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=17"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="58"
			 thickness="2.0"
			 z="34.0"
			 title=""
		>
			<t2_patch
				oid="60"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 18"
				links="57,63"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=18"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="61"
			 thickness="2.0"
			 z="36.0"
			 title=""
		>
			<t2_patch
				oid="63"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 19"
				links="60,66"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=19"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="64"
			 thickness="2.0"
			 z="38.0"
			 title=""
		>
			<t2_patch
				oid="66"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 20"
				links="63,69"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=20"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="67"
			 thickness="2.0"
			 z="40.0"
			 title=""
		>
			<t2_patch
				oid="69"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 21"
				links="66,72"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=21"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="70"
			 thickness="2.0"
			 z="42.0"
			 title=""
		>
			<t2_patch
				oid="72"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 22"
				links="69,75"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=22"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="73"
			 thickness="2.0"
			 z="44.0"
			 title=""
		>
			<t2_patch
				oid="75"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 23"
				links="72,78"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=23"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="76"
			 thickness="2.0"
			 z="46.0"
			 title=""
		>
			<t2_patch
				oid="78"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 24"
				links="75,81"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=24"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="79"
			 thickness="2.0"
			 z="48.0"
			 title=""
		>
			<t2_patch
				oid="81"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 25"
				links="78,84"
				type="1"
				file_path="exp_1_MMStack_Pos0.ome.tif-----#slice=25"
				style="fill-opacity:1.0;stroke:#ffff00;"
				o_width="512"
				o_height="512"
				min="0.0"
				max="47014.0"
				mres="32"
			>
			</t2_patch>
		</t2_layer>
		<t2_layer oid="82"
			 thickness="2.0"
			 z="50.0"
			 title=""
		>
			<t2_patch
				oid="84"
				width="512.0"
				height="512.0"
				transform="matrix(1.0,0.0,0.0,1.0,0.0,0.0)"
				title=" exp_1_MMStack_Pos0.ome 26"